name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set environment variables
      run: echo "DATABASE_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 0

    - name: Install dependencies
      run: |
        cd analyticspages
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations
      run: |
        cd analyticspages
        python manage.py migrate

    - name: Run tests
      run: |
        cd analyticspages
        pytest
